# Netflix Collaborative Filtering

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
import common
import em
from tqdm import tqdm

In [2]:
f_path = "netflix_incomplete.txt"

In [3]:
X = np.loadtxt(f_path)

In [4]:
print(X)

[[2. 4. 5. ... 4. 4. 4.]
 [3. 5. 5. ... 5. 3. 4.]
 [2. 0. 4. ... 4. 4. 3.]
 ...
 [2. 3. 5. ... 3. 4. 2.]
 [3. 4. 0. ... 4. 5. 4.]
 [3. 0. 5. ... 5. 4. 0.]]


In [5]:
X_df = pd.DataFrame(X)

In [8]:
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Columns: 1200 entries, 0 to 1199
dtypes: float64(1200)
memory usage: 11.0 MB


In [6]:
X_df.describe()

0            1            2            3            4     \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000   
mean      2.040000     2.691667     3.587500     2.875833     3.313333   
std       1.453786     1.774605     2.061768     1.536462     1.858683   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000     0.000000     3.000000     3.000000     3.000000   
50%       2.000000     4.000000     5.000000     3.000000     4.000000   
75%       3.000000     4.000000     5.000000     4.000000     5.000000   
max       5.000000     5.000000     5.000000     5.000000     5.000000   

              5            6            7            8            9     ...  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000  ...   
mean      2.216667     3.371667     2.723333     3.224167     2.944167  ...   
std       1.513263     1.621950     1.628086     1.452242     1.205097  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     3.000000     2.000000     3.000000     3.000000  ...   
50%       3.000000     4.000000     3.000000     4.000000     3.000000  ...   
75%       3.000000     5.000000     4.000000     4.000000     4.000000  ...   
max       5.000000     5.000000     5.000000     5.000000     5.000000  ...   

              1190         1191         1192         1193         1194  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000   
mean      2.502500     2.288333     2.513333     2.414167     2.359167   
std       1.703647     1.592894     1.805789     1.553913     1.719776   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000     0.000000     0.000000     1.000000     0.000000   
50%       3.000000     3.000000     3.000000     3.000000     3.000000   
75%       4.000000     4.000000     4.000000     4.000000     4.000000   
max       5.000000     5.000000     5.000000     5.000000     5.000000   

              1195         1196         1197         1198         1199  
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000  
mean      3.159167     2.586667     2.835833     3.302500     2.509167  
std       1.986317     1.833564     1.678163     1.637038     1.589136  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     3.000000     0.000000  
50%       4.000000     3.000000     3.000000     4.000000     3.000000  
75%       5.000000     4.000000     4.000000     4.250000     4.000000  
max       5.000000     5.000000     5.000000     5.000000     5.000000  

[8 rows x 1200 columns]

In [13]:
K = np.array(np.arange(1, 13))

In [14]:
seeds = np.array([0, 1, 2, 3, 4])

In [15]:
# best_seeds = {}

# for k in tqdm(K, desc="Iterating K...", ascii="░▒▓█"):
#     best_ll = np.inf
#     best_seed = None
#     for seed in tqdm(seeds, desc="Identifying best seed...", ascii="░▒▓█"):
#         mixture, post = common.init(X=X, K=k, seed=seed)
#         mixture, post, ll = tqdm(em.run(X=X, post=post, mixture=mixture), desc="Running EM Algorithm...", ascii="░▒▓█")
#         if ll < best_ll:
#             best_ll = ll
#             best_seed = seed
#     print(f"k:{k}")
#     print(f"best_seed:{best_seed}")
#     print(f"best_ll:{best_ll}")
#     best_seeds[k] = dict({"seed": best_seed, "ll": best_ll})


In [16]:
# pd.DataFrame(best_seeds).T.reset_index()

In [17]:
# best_seeds_df = pd.DataFrame(best_seeds).T.reset_index().rename(columns={"index":"K", "seed":"seed", "ll": "ll"})

In [18]:
# best_seeds_df.to_csv('netflix_incomplete_best_seeds_ll.csv', index=False)

In [19]:
best_seeds_df = pd.read_csv('netflix_incomplete_best_seeds_ll.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'netflix_incomplete_best_seeds_ll.csv'

In [ ]:
best_K_seed = best_seeds_df.loc[best_seeds_df['ll'] == np.max(best_seeds_df['ll'])]

In [ ]:
best_K_seed["K"].values[0]

12

In [ ]:
# ll_list = []
# for k,v in best_seeds.items():
#     print(f"v: {v['ll']}")
#     ll_list.append(v['ll'])

In [ ]:
# np.max(ll_list)

In [ ]:
# np.argmax(ll_list) + 1

In [ ]:
# plt.plot(range(1, 13), ll_list)
# plt.scatter(range(1, 13), ll_list, marker='s', label='Best Log-Likelihood')
# _ = plt.xticks(range(1, 13))
# plt.xlabel("K")
# plt.ylabel("Log-Likelihood")
# plt.title("Log-Likelihood of the Best Seeds of the Netflix Incomplete Data")
# plt.grid(True)
# plt.legend()
# plt.show()

In [ ]:
best_K = best_K_seed["K"].values[0]
best_seed = int(best_K_seed["seed"].values[0])
mixture, post = tqdm(common.init(X=X, K=best_K, seed=best_seed), desc="Initializing Mixture...",  ascii="░▒▓█")
mixture, post, ll = tqdm(em.run(X=X, post=post, mixture=mixture), desc="Running EM Algorithm...", ascii="░▒▓█")
X_imputed = em.fill_matrix(X=X, mixture=mixture)
X_imputed_df = pd.DataFrame(X_imputed)
X_imputed_df.describe()

Running EM Algorithm...: 100%|██████████| 3/3 [00:00<00:00, 74898.29it/s]


0              1            2            3            4     \
count  1200.000000   1.200000e+03  1200.000000  1200.000000  1200.000000   
mean      2.638480   3.648385e+00     4.677020     3.541661     4.163288   
std       0.938665   7.322589e-01     0.534339     0.657671     0.765300   
min       1.000000  1.375037e-303     0.000000     0.000000     0.000000   
25%       2.000000   3.271233e+00     4.503733     3.000000     3.894601   
50%       2.831133   4.000000e+00     5.000000     3.350120     4.000000   
75%       3.018229   4.000000e+00     5.000000     4.000000     5.000000   
max       5.000000   5.000000e+00     5.000000     5.000000     5.000000   

              5            6            7            8            9     ...  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000  ...   
mean      2.943608     3.907764     3.268355     3.669493     3.224132  ...   
std       0.831373     0.836613     1.105306     0.807823     0.784445  ...   
min       0.000000     1.000000     1.000000     0.000000     1.000000  ...   
25%       2.480384     3.326021     2.479336     3.000000     3.000000  ...   
50%       3.000000     4.000000     3.000000     4.000000     3.000000  ...   
75%       3.350037     5.000000     4.000000     4.000000     4.000000  ...   
max       5.000000     5.000000     5.000000     5.000000     5.000000  ...   

              1190         1191         1192         1193         1194  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000   
mean      3.298243     3.175701     3.437103     3.126993     3.116441   
std       0.943257     0.702491     0.943427     0.848318     1.065339   
min       0.000000     1.000000     1.000000     0.000000     0.000000   
25%       2.948752     3.000000     2.858824     2.498353     2.685729   
50%       3.000000     3.085835     3.644143     3.000000     3.000000   
75%       4.000000     4.000000     4.000000     4.000000     4.000000   
max       5.000000     5.000000     5.000000     5.000000     5.000000   

              1195         1196         1197         1198         1199  
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000  
mean      4.143756     3.572885     3.594486     3.890179     3.361829  
std       0.872206     0.959174     0.745678     0.833379     0.638017  
min       0.000000     1.000000     1.000000     0.000000     0.000000  
25%       3.711068     3.000000     3.000000     3.000000     3.000000  
50%       4.000000     4.000000     3.784737     4.000000     3.000000  
75%       5.000000     4.126230     4.000000     4.540579     4.000000  
max       5.000000     5.000000     5.000000     5.000000     5.000000  

[8 rows x 1200 columns]

In [ ]:
X_imputed_df.iloc[:,2].argmin()

512

In [ ]:
np.where(X_imputed == 0)

(array([ 162,  162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
         162,  162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
         162,  162,  162,  162,  162,  162,  162,  162,  162,  162,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
         411,  411,  411,  411,  411, 

In [ ]:
X_gold = np.loadtxt('netflix_complete.txt')


In [ ]:
common.rmse(X_gold, X_imputed)

0.4830515038061024